Смоленцев Р.Ю - pack-rle - 3530901/10006
AbdullinAM/programming-task2-2022 pull request #3
Opened 2022-03-11 23:03 UTC by rsmolentsev

Меня сильно смущает действие, которое на скрине, потому что не нашёл, как можно (если можно) эффективнее обрабатывать случай с пустой строкой в файле, чтобы при встрече пустой строки программа не выдала мне ошибку. Подскажите, пожалуйста, если вариант реализовать получше существует.
![Empty String](https://user-images.githubusercontent.com/90306540/157985703-eb54bf9c-6f20-47a8-9e14-62501e83240d.jpg)

2022-03-21 11:55 UTC, AbdullinAM requested changes

2022-03-21 11:55 UTC, AbdullinAM commented on app/src/main/java/programming/task2/PackRLE.java
> +            else {
Подобные конструкции можно объединять в один `if - else if`:
```
if (...) {
    ...
} else if (...) {
    ...
} ...
```

2022-03-21 11:55 UTC, AbdullinAM commented on app/src/main/java/programming/task2/PackRLE.java
> +                    unpackResult.append(new String(new char[Integer.parseInt(digitSequence.toString())]).replace('\0', c));
Такие длинные конструкции лучше разделять на несколько строк

2022-03-21 11:55 UTC, AbdullinAM commented on app/src/main/java/programming/task2/PackRLE.java
> +                    unpackResult.append(new String(new char[Integer.parseInt(digitSequence.toString())]).replace('\0', c));
А вообще, зачем такая сложная конструкция. Сначала вы выделяете память создаев массив. Потом еще раз ее перевыделяете создав строку из массива. А потом еще идете и перезаписываете всю эту память через replace. Лучше использовать обычный цикл

2022-03-21 11:55 UTC, AbdullinAM commented on app/src/main/resources/testRes/input1.txt
> +BBBBBBBBBBBBIIIIIIIIIIIGGGG DUBBBB MMMMMAAAAAAAAAAAATTTTTTEEEEEEEEE
Файлы с тестовыми ресурсами лучше класть в папку `src/test/resources`. Тогда они будут включены только в тестовой сборке. Файлы из `src/main/resources` же включаются в основной jar файл вашего приложения. Нет нужды класть туда ненужные файлы

2022-03-21 11:55 UTC, AbdullinAM commented on app/src/main/java/programming/task2/PackRLE.java
> +    public String packer(String content) {
Как ваше приложение отработает если подать в него файл с цифрами? Нужно как-то обработать эту ситуацию. Например, выдавать ошибку

2022-03-21 11:55 UTC, AbdullinAM commented on app/src/test/java/programming/task2/PackRLETests.java
> +public class PackRLETests {
Нужно больше тестов на парсинг аргументов и взаимодействие с системой. Что будет с неправильными аргументами, что будет если файлы не найдутся и т.д.

2022-03-27 17:41 UTC, rsmolentsev commented
Готово к проверке

2022-03-28 10:53 UTC, AbdullinAM commented
Задание предварительно принято с оценкой 5. Для того чтобы оценка была окончательной вам нужно будет на паре "защитить" свое решение --- показать что вы его понимаете и умеете с ним работать. Это можно сделать на любой паре до конца семестра.

На следующем занятии расскажу про 3 задание и дам примеры вариантов

2022-03-28 10:53 UTC, AbdullinAM approved these changes

2022-04-04 11:15 UTC, AbdullinAM commented
Зачтено с оценкой 5

2022-04-04 11:15 UTC, closed without merging