Денисов В. А. - ls - 3530901/10006
AbdullinAM/programming-task2-2022 pull request #4
Opened 2022-03-19 14:27 UTC by vladdenisov

2022-03-25 10:16 UTC, AbdullinAM requested changes

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +import com.github.ajalt.clikt.core.CliktCommand
В целом у вас все хорошо, но в вашем "процедурном" подходе есть один минус: ваш код не очень удобно будет использовать программно. Потому что все ваши функции работают с обычными строками и числами, которые никак не структурированы. В описании задания есть строчка "При проектировании использовать объектно-ориентированный подход". Это предполагает что вам нужно было выделить основные сущности используемые в вашем приложении и написать код который позволяет взаимодействовать с этими сущностями

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +fun permissionsFallback(file: File, numeric: Boolean? = false): String {
Почему `numeric` --- nullable?

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +    if (numeric == true) {
В таком коде можно использовать if expression:
```
return if (...) A else B
```

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +fun displayPermissions(file: File, numeric: Boolean? = false): String {
Зачем вам два куска кода которые делают, по сути, одно и то же?

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +    if (isHuman) {
if expression

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +    if (files === null) return listOf("")
Почему ===?

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +    private val path: Path by argument("Path", "Path to folder").path(canBeFile = false, mustExist = true).default(Paths.get("").toAbsolutePath())
В задании вам явно указано что водной аргумент может быть просто файлом

2022-03-25 10:16 UTC, AbdullinAM commented on src/main/kotlin/Main.kt
> +fun mainWithoutLibraryExceptionHandler(args: Array<String>) = LS().parse(args)
А чем отличаются эти два мейна?

2022-03-25 10:16 UTC, AbdullinAM commented on src/test/kotlin/Tests.kt
> +            File("./build/tempTest/1.txt").appendText("TEST EXAMPLE FILE")
Хотелось бы больше проверок на разного рода файлах. И пустые файлы, и директории и т.д.

2022-03-25 12:55 UTC, vladdenisov commented on src/main/kotlin/Main.kt
> +fun mainWithoutLibraryExceptionHandler(args: Array<String>) = LS().parse(args)
Второй main используется для тестирования, в случае вызова `parse` встроенный в библиотеку хэндлер ошибок не используется, что позволяет проверять корректность типа исключений, выбрасываемых при парсе аргументов библиотекой.

2022-03-25 13:07 UTC, vladdenisov commented on src/main/kotlin/Main.kt
> +fun displayPermissions(file: File, numeric: Boolean? = false): String {
Если вы про две функции для получения правил доступа для файла, то сначала отрабатывает `displayPermissions`, однако, если это не `Unix` система, то `getPosixFilePermissions` на ней не сработает и выбросит исключение, тогда используется `permissionsFallback`, которая лишь проверяет права `drwx`, без разделения на права разных групп.

2022-03-25 13:08 UTC, vladdenisov commented on src/main/kotlin/Main.kt
> +fun permissionsFallback(file: File, numeric: Boolean? = false): String {
Забыл поменять после перехода на библиотеку для парсинга аргументов

2022-03-25 13:09 UTC, vladdenisov commented on src/main/kotlin/Main.kt
> +import com.github.ajalt.clikt.core.CliktCommand
Хорошо, поработаю над этим!

2022-03-25 13:12 UTC, vladdenisov commented on src/main/kotlin/Main.kt
> +    if (files === null) return listOf("")
Параллельно работал ещё над проектом на `Javascript`, поэтому тут и такие неожиданные моменты появляются (тройные равно и т.д)

2022-03-25 13:18 UTC, vladdenisov commented on src/main/kotlin/Main.kt
> +    private val path: Path by argument("Path", "Path to folder").path(canBeFile = false, mustExist = true).default(Paths.get("").toAbsolutePath())
прошу прощения, не заметил

2022-04-04 08:54 UTC, AbdullinAM approved these changes

2022-04-04 08:55 UTC, AbdullinAM commented
По коду замечаний больше нет, нужно теперь провести "защиту" на паре

2022-04-04 11:43 UTC, AbdullinAM commented
Зачтено с оценкой 5

2022-04-04 11:43 UTC, closed without merging